NUM_SAMPLES=5000
NUM_SAMPLES_TEST=20000
NUM_EPOCHS=100000
CLASSES="0,1,2,3,4,5,6,7,8,9"
MEANS="-1,1"
STD=1
MU_T_SCHEDULAR="linear"
CONDITION_TYPE="unconditional"
PREDICTION_TYPE="standard_noise"
#DATASET="huggan/AFHQv2"
#DATASET="jxie/celeba-hq"
#DATASET="cifar10"
#DATASET="mnist"
DATASET="/nas/dataset/daeun/raw_images/cifar10-32-perclass3000-30000/"
OUTPUT_DIR="20240805_${CONDITION_TYPE}_shuffle_${PREDICTION_TYPE}_cifar10_class${CLASSES}_${NUM_SAMPLES}samples_std${STD}_epoch${NUM_EPOCHS}_minmaxscaling/${MU_T_SCHEDULAR}_mean${MEANS}"

CUDA_VISIBLE_DEVICES=1 python evaluate.py \
  --dataset_name=$DATASET \
  --resolution=32 \
  --output_dir=$OUTPUT_DIR \
  --fid_batch_size=100 \
  --fid_total_size=$NUM_SAMPLES \
  --target_classes=$CLASSES \
  --samples_per_class_train=$NUM_SAMPLES \
  --samples_per_class_test=$NUM_SAMPLES_TEST \
  --samples_per_train_subset=$NUM_SAMPLES \
  --samples_per_test_subset=$NUM_SAMPLES_TEST \
  --target_noise_means_input=$MEANS \
  --target_noise_std=$STD \
  --condition_type=$CONDITION_TYPE \
  --prdc_batch_size=4 \
  --num_checkpoint=16875000