NUM_SAMPLES=1024
NUM_EPOCHS=10000
CLASSES="0,1"
MEANS="0,0"
STD=1
MU_T_SCHEDULAR="ddpm"
CONDITION_TYPE="unconditional"
PREDICTION_TYPE="standard_noise"
#DATASET="huggan/AFHQv2"
#DATASET="jxie/celeba-hq"
#DATASET="cifar10"
#DATASET="mnist"
DATASET="/nas/dataset/daeun/raw_images/cifar10-32-perclass1024-2048/train/"
OUTPUT_DIR="20240806_${CONDITION_TYPE}_shuffle_${PREDICTION_TYPE}_cifar10_class${CLASSES}_${NUM_SAMPLES}samples_std${STD}_epoch${NUM_EPOCHS}_minmaxscaling/${MU_T_SCHEDULAR}_mean${MEANS}"

CUDA_VISIBLE_DEVICES=3 accelerate launch seperated_ddpm.py \
  --dataset_name=$DATASET \
  --resolution=32 \
  --output_dir=$OUTPUT_DIR \
  --train_batch_size=16 \
  --eval_batch_size=25 \
  --num_epochs=$NUM_EPOCHS \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-4 \
  --lr_warmup_steps=500 \
  --mixed_precision=no \
  --logger="wandb" \
  --checkpointing_steps=-1 \
  --checkpoints_total_limit=10 \
  --save_model_epochs=1000 \
  --target_classes=$CLASSES \
  --samples_per_subset=$NUM_SAMPLES \
  --target_noise_means_input=$MEANS \
  --target_noise_std=$STD \
  --prediction_type=$PREDICTION_TYPE \
  --mu_t_schedular=$MU_T_SCHEDULAR \
  --scale_factor_sigmoid=10 \
  --condition_type=$CONDITION_TYPE \
  --shuffle_noise_means